version: "3.9"

services:

  postgres_db:
    image: postgres:alpine
    container_name: "postgres"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=akatsuki
    deploy:
      restart_policy:
        condition: on-failure

  server:
    build: .
    image: akatsuki
    container_name: "rest_api_server"
    ports:
      - "8081:8081"
    # env values already taken from .env
    depends_on:
      - postgres_db

volumes:
  database_postgres:
